# Generated by Django 5.0.7 on 2024-08-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsv1', '0002_student_noofhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='clubId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubsv1.club'),
        ),
    ]
