# Generated by Django 5.0.7 on 2024-08-19 05:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsv1', '0002_alter_student_dob_alter_student_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='BatchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubsv1.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ClubId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubsv1.club'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('IT', 'IT'), ('AIDS', 'AIDS')], default='SNH', max_length=100)),
                ('quota', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubsv1.batch')),
                ('clubId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubsv1.club')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubsv1.yeardata')),
            ],
        ),
    ]
